# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Text', models.CharField(max_length=2000)),
                ('Start', models.DateField()),
                ('End', models.DateField()),
                ('Pub_date', models.DateField()),
                ('Pub_end', models.DateField()),
            ],
        ),
    ]
