# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visthuset_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
